spring:
  profiles:
    active: dev
  application:
    name: lsl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  pid:
    file: app.pid

server:
  port: 12366
